/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as RegisterRouteRouteImport } from './routes/register.route'
import { Route as LoginRouteRouteImport } from './routes/login.route'
import { Route as IndexRouteRouteImport } from './routes/index.route'
import { Route as ActivateConectamaisRouteRouteImport } from './routes/activate/conectamais.route'
import { Route as AuthenticatedProfileRouteRouteImport } from './routes/_authenticated/profile.route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard.route'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateConectamaisRouteRoute =
  ActivateConectamaisRouteRouteImport.update({
    id: '/activate/conectamais',
    path: '/activate/conectamais',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileRouteRoute =
  AuthenticatedProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/profile': typeof AuthenticatedProfileRouteRoute
  '/activate/conectamais': typeof ActivateConectamaisRouteRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/profile': typeof AuthenticatedProfileRouteRoute
  '/activate/conectamais': typeof ActivateConectamaisRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteRoute
  '/activate/conectamais': typeof ActivateConectamaisRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/activate/conectamais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/activate/conectamais'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/activate/conectamais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  RegisterRouteRoute: typeof RegisterRouteRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ActivateConectamaisRouteRoute: typeof ActivateConectamaisRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/conectamais': {
      id: '/activate/conectamais'
      path: '/activate/conectamais'
      fullPath: '/activate/conectamais'
      preLoaderRoute: typeof ActivateConectamaisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
  AuthenticatedProfileRouteRoute: typeof AuthenticatedProfileRouteRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedProfileRouteRoute: AuthenticatedProfileRouteRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  RegisterRouteRoute: RegisterRouteRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ActivateConectamaisRouteRoute: ActivateConectamaisRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
